import { Canvas, useFrame } from "@react-three/fiber";
import { Float, OrbitControls, Sparkles, Text } from "@react-three/drei";
import { useMemo, useRef } from "react";
import type { Group, Mesh } from "three";

type SpatialCoreProps = { tasks: number; goals: number; roadmap: number; onNavigate: (view: "Tasks" | "Goals" | "Roadmap" | "Schedule" | "Analytics" | "Profile") => void };
const nodes = [
  { label: "TASKS", view: "Tasks" as const, position: [-2.25, 0.85, 0.2] as [number, number, number], color: "#fbbf24" },
  { label: "GOALS", view: "Goals" as const, position: [2.25, 0.85, 0.2] as [number, number, number], color: "#fb7185" },
  { label: "ROADMAP", view: "Roadmap" as const, position: [0, 2.05, -0.05] as [number, number, number], color: "#a78bfa" },
  { label: "SCHEDULE", view: "Schedule" as const, position: [-2.25, -0.95, 0.2] as [number, number, number], color: "#67e8f9" },
  { label: "ANALYTICS", view: "Analytics" as const, position: [2.25, -0.95, 0.2] as [number, number, number], color: "#86efac" },
  { label: "PROFILE", view: "Profile" as const, position: [0, -2.05, -0.05] as [number, number, number], color: "#c4b5fd" },
];
function Core({ onNavigate }: { onNavigate: SpatialCoreProps["onNavigate"] }) { const ref = useRef<Group>(null); useFrame((_, delta) => { if (ref.current && !window.matchMedia("(prefers-reduced-motion: reduce)").matches) ref.current.rotation.y += delta * 0.08; }); return <group ref={ref}><mesh><sphereGeometry args={[0.7, 32, 32]} /><meshStandardMaterial color="#211744" emissive="#8b5cf6" emissiveIntensity={1.15} metalness={0.7} roughness={0.25} /></mesh><mesh scale={0.62}><sphereGeometry args={[1, 24, 24]} /><meshBasicMaterial color="#d8b4fe" wireframe transparent opacity={0.45} /></mesh><Text position={[0, 0, 0.72]} fontSize={0.16} color="#f5f3ff" anchorX="center" anchorY="middle">COSMOS</Text>{nodes.map(node => <OrbitalNode key={node.label} {...node} onClick={() => onNavigate(node.view)} />)}</group>; }
function OrbitalNode({ label, position, color, onClick }: { label: string; position: [number, number, number]; color: string; onClick: () => void }) { const ref = useRef<Mesh>(null); const pulse = useMemo(() => 1 + Math.random() * 0.2, []); useFrame(({ clock }) => { if (ref.current && !window.matchMedia("(prefers-reduced-motion: reduce)").matches) { const scale = 1 + Math.sin(clock.elapsedTime * 1.6 + pulse) * 0.045; ref.current.scale.setScalar(scale); } }); return <group position={position}><mesh ref={ref} onClick={onClick} onPointerOver={e => { e.stopPropagation(); document.body.style.cursor = "pointer"; }} onPointerOut={() => { document.body.style.cursor = ""; }}><sphereGeometry args={[0.24, 20, 20]} /><meshStandardMaterial color={color} emissive={color} emissiveIntensity={0.8} metalness={0.5} roughness={0.3} /></mesh><Text position={[0, -0.46, 0]} fontSize={0.12} color="#bbb6d6" anchorX="center" anchorY="middle">{label}</Text></group>; }
function OrbitPaths() { return <>{[1.5, 2.45].map((radius, i) => <mesh key={radius} rotation={[Math.PI / 2, 0, i * 0.45]}><torusGeometry args={[radius, 0.008, 8, 96]} /><meshBasicMaterial color={i ? "#67e8f9" : "#a78bfa"} transparent opacity={0.2} /></mesh>)}</>; }
export function SpatialCore({ tasks, goals, roadmap, onNavigate }: SpatialCoreProps) { return <section className="spatial-panel" aria-label="Interactive COSMOS spatial map"><div className="spatial-copy"><span className="eyebrow">SPATIAL COMMAND CENTER</span><h3>Navigate your academic universe</h3><p>Click an orbital module to open its normal workspace view.</p><div className="spatial-stats"><span><strong>{tasks}</strong> open tasks</span><span><strong>{goals}</strong> goals</span><span><strong>{roadmap}%</strong> roadmap</span></div></div><div className="spatial-canvas"><Canvas camera={{ position: [0, 0, 7], fov: 42 }} dpr={[1, 1.5]} gl={{ antialias: true, powerPreference: "high-performance" }}><ambientLight intensity={0.7} /><pointLight position={[2, 3, 4]} intensity={18} color="#a78bfa" /><pointLight position={[-3, -2, 2]} intensity={10} color="#67e8f9" /><Sparkles count={35} scale={7} size={1.8} speed={0.18} color="#c4b5fd" /><OrbitPaths /><Float speed={0.7} rotationIntensity={0.1} floatIntensity={0.18}><Core onNavigate={onNavigate} /></Float><OrbitControls enablePan={false} minDistance={5.5} maxDistance={8} autoRotate={false} /></Canvas></div></section>; }
